### ISSUE TITLE
Thanks all!

### ISSUE THREAD

**Issue by end3r** [GamedevJS/Gamedev.js-Survey#14]
Hey @Abdallah-Alwarawreh, @xem, @riidom, @verekia, @darshanrane, @juhair-cupcake, @denis3denis, @federicojacobi - thanks so much for helping with the 2023 Survey questions!

Please email me at `contact@gamedevjs.com` with your GitHub username and PayPal ID so I can wire you $50 each.

**Comment by Abdallah-Alwarawreh** [comment]
Hey there! Delighted to contribute to the 2023 Survey questions.

**Comment by riidom** [comment]
Thanks as well. I'd also like to see my share donated. It is winter, and not everyone has a heated room.

**Comment by end3r** [comment]
All cases solved - closing the issue.
